version: '3.8'

services:
  web:
    image: countdown:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1519:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped

