version: '3.8'

services:
  web:
    image: countdown:latest  # Ensure this matches the tag used during docker build
    build:
      context: .  # Context is the directory containing Dockerfile and nginx.conf
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./dist:/usr/share/nginx/html  # Map the dist folder to Nginx's serve directory
    restart: unless-stopped  # Option to always restart unless stopped manually

